export const QUERY_KEYS = {
  GET_PROFILE: "GET_PROFILE",
  GET_SOLD: "GET_SOLD",
  GET_AVAILABLE: "GET_AVAILABLE",
  GET_VIEWS: "GET_VIEWS",
  GET_VISITOS_GRAPHICS: "GET_VISITOS_GRAPHICS",
  GET_ALL_PRODUCTS: "GET_ALL_PRODUCTS",
  GET_CATEGORIES: "GET_CATEGORIES",
  GET_PRODUCT_DETAIL: "GET_PRODUCT_DETAIL"
};
